naja_web/naja_web/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('web_users.urls')),
    #url(r'^admin/', admin.site.urls),
]

naja_web/web_users/urls.py
from django.conf.urls import url

from . import views
from . import forms
from . import models

urlpatterns = [
    url(r'^home/', views.home, name='home'),

    url(r'^plugin/list/', views.MyListView.as_view(
        template_name='plugin_list.html',
        model=models.Plugin,
        paginate_by=10,
    ), name='plugin_list'),

    url(r'^plugin/create/', views.MyCreateView.as_view(
        model=models.Plugin,
        template_name='plugin_create.html',
        form_class=forms.PluginForm,
        success_url='plugin_details',
    ), name='plugin_create'),

    url(r'^plugin/details/(?P<pk>\d+)', views.MyDetailView.as_view(
        template_name='plugin_details.html',
        model=models.Plugin,
    ), name='plugin_details'),


    url(r'^task/create/', views.MyCreateView.as_view(
        template_name='task_create.html',
        form_class=forms.TaskForm,
        success_url='task_details',
    ), name='task_create'),

    url(r'^task/details/(?P<pk>\d+)', views.MyDetailView.as_view(
        template_name='task_details.html',
        model=models.Task,
    ), name='task_details'),

    url(r'^task/list/', views.MyListView.as_view(
        template_name='task_list.html',
        model=models.Task,
        paginate_by=10,
    ), name='task_list'),







    url(r'^task/list/', views.task_list, name='task_list'),
    url(r'^task/details/', views.task_details, name='task_details'),
    url(r'^bug/list/$', views.PluginList.as_view(), name='bug_list'),


]

'''





    # 列表
    url(r'^targets/list/', MyListView.as_view(
        template_name='targets_list.html',
        model=Targets,
        paginate_by=15
    ), name='targets_list'),
    # 详细信息
    url(r'^targets/details/(?P<pk>\d+)', login_required(MyDetailView.as_view(
        template_name='targets_details.html',
        model=Targets,
    )), name='targets_details'),
    # 创建
    url(r'^targets/create/', login_required(MyCreateView.as_view(
        template_name='targets_create.html',
        form_class=TargetsForm,
        success_url='targets_details',
    )), name='targets_create'),
    # 更新
    url(r'^targets/update/(?P<pk>\d+)', login_required(MyUpdateView.as_view(
        template_name='targets_update.html',
        form_class=TargetsForm,
        model=Targets,
        success_url='targets_details',
    )), name='targets_update'),
    # 删除
    url(r'^targets/delete/(?P<pk>\d+)', login_required(MyDeleteView.as_view(
        template_name = 'targets_delete.html',
        model=Targets,
        success_url = reverse_lazy('targets_list')
    )), name='targets_delete'),

'''

naja_web/web_users/models.py
from django.db import models
from django.core.validators import MaxValueValidator


class Bugs(models.Model):
    country = models.CharField(max_length=256)
    host = models.CharField(max_length=256)
    bug_name = models.CharField(max_length=256)
    bug_class = models.CharField(max_length=256)
    road = models.CharField(max_length=256)
    last_time = models.CharField(max_length=256)
    usable = models.CharField(max_length=256)
    information = models.CharField(max_length=65535)
    author = models.CharField(max_length=256)
    class Meta:
        db_table = 'Bugs'  # 数据表名称


class Plugin(models.Model):
    name = models.CharField(max_length=256)
    type_type = (
        ('COM', '通用插件'),
        ('POC', '漏洞探测插件'),
        ('EXP', '漏洞利用插件'),
    )
    type = models.CharField(max_length=3, choices=type_type)
    risk_type = (
        ('H', '高危'), # 代码执行
        ('M', '中危'), # 写权限 数据库 内存 文件系统
        ('L', '低危'), # 读取服务器上的信息 数据库 内存 文件系统  DDOS
        ('I', '信息'), # 端口扫描 指纹识别
    )
    risk = models.CharField(max_length=4, choices=risk_type)

    '''
    grade_type = (
        (0, 'target'),      # 00000001      target_common target_google target_zoomeye target_shodan
        (1, 'Host'),        # 00000001      nmap
        (2, 'Port'),        # 00000010
        (4, 'Proto'),       # 00000100      ms17-010
        (8, 'Service'),     # 00001000      spider
        (16, 'SBanner'),    # 00010000      WFTP-RCE
        (32, 'URL'),        # 00100000      SQL注入
        (64, 'UBanner'),    # 01000000      S-020 Jeklins-SQL
    )
    grade = models.PositiveSmallIntegerField(default=1, choices=grade_type)
    '''
    usage = models.TextField()
    description = models.TextField()
    exec_path = models.CharField(max_length=256)

    class Meta:
        db_table = 'Plugin'  # 数据表名称

    def __str__(self):
        # 用于Forms显示外键内容
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=256)
    targets = models.TextField()
    count = models.IntegerField(default=-1)
    timestamp = models.TimeField(auto_now_add=True)
    status_type = (
        ('S', '扫描中'),
        ('F', '已完成'),
        ('E', '异常终止'),
    )
    #bug_count = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=1, choices=status_type)
    plugin = models.ManyToManyField(Plugin)

    class Meta:
        db_table = 'Task'  # 数据表名称

naja_web/web_users/forms.py
from django import forms

from django.forms import widgets

from . import models

class MyCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    template_name = 'widgets/multiple_input.html'
    option_template_name = 'widgets/input_option.html'

class TaskForm(forms.ModelForm):

    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "任务名称"}),
    )

    targets = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'placeholder': "目标列表"}),
    )

    plugin = forms.ModelMultipleChoiceField(
        # 外键的初始化
        queryset= models.Plugin.objects.all(),  # TODO 减少查询列
        # 自定义Widget样式 TODO:总结
        widget=MyCheckboxSelectMultiple(attrs={'sonclass': 'checkbox-inline', 'grandsonclass': 'label label-default'}),
    )
    class Meta:
        model = models.Task
        fields = ['name', 'targets', 'plugin']

class PluginForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "插件名称"}),
    )
    type = forms.ChoiceField(
        choices=models.Plugin.type_type,
        widget=forms.Select(attrs={'class': 'form-control', }),
    )
    risk = forms.ChoiceField(
        choices=models.Plugin.risk_type,
        widget=forms.Select(attrs={'class': 'form-control', }),
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'placeholder': "插件描述"}),
    )
    usage = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'placeholder': "使用方法"}),
    )
    exec_path = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "/plugins/*.py"}),
    )

    class Meta:
        model = models.Plugin
        fields = ['name', 'type', 'risk', 'description', 'usage', 'exec_path']

naja_web/web_users/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.urls import reverse

from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

from . import models


# 查询列表
class MyListView(ListView):
    # 读取所有数据记录
    def get_queryset(self):
        return self.model.objects.all()

# 查询详细信息
class MyDetailView(DetailView):
    # 查询当前数据记录
    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['pk'])

# 增
class MyCreateView(CreateView):
    def get_success_url(self):
        return reverse(self.success_url, args=(str(self.object.pk), ))

# 删
class MyDeleteView(DeleteView):
    def get_object(self, queryset=None):
        return super(MyDeleteView, self).get_object()

# 改
class MyUpdateView(UpdateView):
    # 查询当前数据记录
    def get_object(self, queryset=None):
        return self.model.objects.get(pk=self.kwargs['pk'])

    # 自定义success_url
    def get_success_url(self):
        return reverse(self.success_url, args=(str(self.kwargs['pk']), ))



class BugsList(ListView):
    model = models.Bugs
    template_name = 'bug_list.html'

class PluginList(ListView):
    model = models.Plugin
    template_name = 'bug_list.html'


def task_list(request):
    return render(request, "task_list.html")
    #return HttpResponse("Hello, naja web users.")

def task_details(request):
    return render(request, "task_details.html")

def task_create(request):
    return render(request, "task_create.html")

def bug_list(request):
    return render(request, "bug_list.html")


def home(request):
    return render(request, "home.html")

naja_web/web_users/templates/base_site.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>naja Scanner</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'bootstrap/3.3.7/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'sticky-footer-navbar.css' %}" rel="stylesheet">
    <!-- Fontawesome -->
    <link href="{% static 'font-awesome/4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" >

  </head>

  <body>

    <!-- Fixed navbar -->
    {% block navbar %}
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-ils" aria-hidden="true"></i>Scanner</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">任务管理<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'task_list' %}">任务列表</a></li>
                <li><a href="{% url 'task_create' %}">新建任务</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'task_create' %}">任务日志</a></li>
              </ul>
            </li>

            <li><a href="#">漏洞库</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">插件管理<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'plugin_list' %}">插件列表</a></li>
                <li><a href="{% url 'plugin_create' %}">新增插件</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">二次开发文档</a></li>
              </ul>
            </li>


            <li><a href="#">帮助</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">登陆</a></li>
            <li><a href="#">注册</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}
    <footer class="footer">
      <div class="container">
        <p class="text-muted">NaJa Scanner - A bug scanner easy to use.</p>
      </div>
    </footer>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'jquery/3.2.1/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/3.3.7/js/bootstrap.min.js' %}"></script>

  </body>
</html>

naja_web/web_users/templates/bug_list.html
{% extends 'base_site.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">

      <div class="page-header">
        <ol class="breadcrumb">
          <li><a href="#">主页</a></li>
          <li><a href="#">漏洞库</a></li>
          <li class="active">漏洞列表</li>
        </ol>

        <form class="form-horizontal">
          <div class="form-group">

            <div class="col-sm-3">
              <input type="email" class="form-control" id="inputEmail3" placeholder="主机、国家或漏洞名称">
            </div>
            <div class="col-sm-1">
              <a  type="submit" class="btn btn-sm btn-success">搜索</a>
            </div>
          </div>
          <div class="form-group">

            <div class="col-sm-12">
              <span class="label label-default">Search:</span>
              <span class="label label-success">host:202.*</span>
              <span class="label label-success">bug:ms17-010</span>
              <span class="label label-success">country:美国</span>
              <span class="label label-success">Port:80</span>
            </div>
          </div>

        </form>

      </div>

      <!-- start user projects -->
      <table class="data table table-striped">
        <thead>
          <tr>
            <th>地区</th>
            <th>主机</th>
            <th>Port</th>
            <th>漏洞</th>
            <th>路径</th>
            <th>最近发现时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for bug in object_list %}
          <tr>
            <td>{{ bug.country }}</td>
            <td>{{ bug.host }}</td>
            <td>{{ bug.port }}</td>
            <td>
              <ul class="list-inline">
                <li>
                  <span class="label label-default">{{ bug.bug_name }}</span>
                  <span class="label label-danger">{{ bug.bug_class }}</span>
                </li>

              </ul>
            </td>
            <td>{{ bug.road }}</td>
            <td>
              <ul class="list-inline">
                <li>
                  <span class="label label-default">{{ bug.last_time }}</span>
                  <span class="label label-success">{{ bug.usable }}</span>
                </li>

              </ul>
            </td>
            <td>
              <a href="task_host_details.html" class="btn btn-default btn-xs">详情</a>
              <a href="task_host_details.html" class="btn btn-danger btn-xs">更新</a>
              <a href="task_host_details.html" class="btn btn-warning btn-xs">删除</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <!-- end user projects -->


      <div class="page-header"></div>


      <nav aria-label="...">
        <ul class="pager">
          <li class="previous"><a href="#">上一页</a></li>
          <li class="next"><a href="#">下一页</a></li>
        </ul>
      </nav>


    </div>
{% endblock %}

naja_web/web_users/templates/home.html
{% extends 'base_site.html' %}
{% block content %}


<div class="container theme-showcase" role="main">

    <div class="col-md-8 col-md-offset-2 col-xs-12">
        <form class="form-horizontal">
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group"></div>
          <div class="form-group">
              <div class="input-group" v-if="inputType=='urlpath' && websiteConfig.name!='CMDChop'">
                  <span class="input-group-addon" id="basic-addon1">关键词</span>
                  <input type="text" class="form-control" placeholder="{{ websiteConfig.inputHint }}" v-model="input" >
              </div>
          </div>
          <div class="form-group">
              <button type="button" class="btn btn-chop pull-right" v-on:click="submitPayload">搜索</button>
          </div>
          <div class="form-group">
            <ul class="list-inline" id="samples_ul">
                <li class="sample_text">Samples:</li>
                <li class="sample_cases" v-for="sample in samples">
                    <code><a v-text="sample.payload" v-on:click="submitSample(sample.payload, sample.type)">MS17-010</a></code>
                </li>
            </ul>
          </div>

        </form>
    </div>
</div>
{% endblock %}

naja_web/web_users/templates/plugin_details.html
{% extends 'base_site.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">

    <div class="page-header">
        <ol class="breadcrumb">
          <li><a href="{% url 'home' %}">主页</a></li>
          <li><a href="{% url 'plugin_list' %}">插件管理</a></li>
          <li class="active">{{ object.name }}</li>
        </ol>
        <small>基本信息</small>
    </div>

    <form class="form-horizontal">

      <div class="form-group">
        <label class="col-sm-1 control-label">插件名称</label>
        <div class="col-sm-6">
            <label class="checkbox-inline">
                <span class="label label-default">{{ object.name }}</span>
            </label>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-1 control-label">插件类型</label>
        <div class="col-sm-6">
            <label class="checkbox-inline">
                {{ object.get_type_display }}
                <span class="label label-danger">{{ object.get_risk_display }}</span>
            </label>
        </div>
      </div>
    </form>
    <div class="page-header">
        <small>特殊选项</small>
    </div>
    <form class="form-horizontal">

      <div class="form-group">
        <label class="col-sm-1 control-label">插件级别</label>
        <div class="col-sm-6">
            <label class="checkbox-inline">
                {% if object.need == 'H'  %}
                    <span class="label label-danger">Host</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Port</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Service</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Banner</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">URL</span>
                {% elif object.need == 'P'  %}
                    <span class="label label-danger">Host</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Port</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Service</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Banner</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">URL</span>
                {% elif object.need == 'S'  %}
                    <span class="label label-danger">Host</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Port</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Service</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">Banner</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">URL</span>
                {% elif object.need == 'B'  %}
                    <span class="label label-danger">Host</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Port</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Service</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Banner</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-success">URL</span>
                {% elif object.need == 'U'  %}
                    <span class="label label-danger">Host</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Port</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Service</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">Banner</span>
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    <span class="label label-danger">URL</span>
                {% endif %}
                <small>{{ object.get_need_display }}</small>
            </label>
        </div>
      </div>
    </form>


    <div class="page-header">
        <small>调用说明</small>
    </div>
    <p>
        {{ object.usage }}
    </p>

    <ol class="breadcrumb">
        {{ object.result }}
    </ol>

    <div class="page-header">
        <small>插件介绍</small>
    </div>
    <ol class="breadcrumb">
        {{ object.description }}
    </ol>
    <div class="page-header"></div>

    <a class="btn btn-success" href="#">下载插件</a>
    <a class="btn btn-danger" href="#">删除</a>


    </div>
{% endblock %}

naja_web/web_users/templates/plugin_list.html
{% extends 'base_site.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">

      <div class="page-header">
        <ol class="breadcrumb">
          <li><a href="#">主页</a></li>
          <li><a href="#">插件管理</a></li>
          <li class="active">插件列表</li>
        </ol>
        <form class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-3">
              <input type="email" class="form-control" id="inputEmail3" placeholder="插件名称、类型、级别">
            </div>
            <div class="col-sm-1">
              <a  type="submit" class="btn btn-sm btn-success">搜索</a>
            </div>
          </div>
          <div class="form-group">

            <div class="col-sm-12">
              <span class="label label-default">Search:</span>
              <span class="label label-success">ms17-010</span>
              <span class="label label-success">type:远程代码执行</span>
            </div>
          </div>
        </form>
      </div>
      <!-- start user projects -->
      <table class="data table table-striped">
        <thead>
          <tr>
            <th>插件名称</th>
            <th>插件类型</th>
            <th>插件级别</th>
            <th>说明</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{ object.name }}</td>
            <td>
              <ul class="list-inline">
                <li>
                  <span class="label label-default">{{ object.get_type_display }}</span>
                  <span class="label label-danger">{{ object.get_risk_display }}</span>
                </li>
              </ul>
            </td>
            <td>
                <span class="label label-danger">Host</span>
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                <span class="label label-danger">Port</span>
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                <span class="label label-success">Service</span>
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                <span class="label label-success">Banner</span>
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                <span class="label label-success">URL</span>
            </td>
            <td>{{ object.description }}</td>
            <td>
              <a href="/plugin/details/{{ object.id }}" class="btn btn-default btn-xs">详情</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="page-header"></div>
      {% if is_paginated %}
          <ul class="pager">
          {% if page_obj.has_previous %}
            <li class="previous"><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">上一页</a></li>
          {% endif %}
          {% if page_obj.has_next %}
            <li class="next"><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">下一页</a></li>
          {% endif %}
          </ul>
      {% endif %}
    </div>
{% endblock %}

naja_web/web_users/templates/task_list.html
{% extends 'base_site.html' %}
{% block content %}
    <div class="container theme-showcase" role="main">
      <div class="page-header">
        <ol class="breadcrumb">
          <li><a href="#">主页</a></li>
          <li><a href="#">任务管理</a></li>
          <li class="active">任务列表</li>
        </ol>

        <form class="form-horizontal">
          <div class="form-group">

            <div class="col-sm-3">
              <input type="email" class="form-control" placeholder="任务名称、包含主机、插件">
            </div>
            <div class="col-sm-1">
              <a  type="submit" class="btn btn-sm btn-success">搜索</a>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <span class="label label-default">Search:</span>
              <span class="label label-success">ms17-010国内扫描</span>
              <span class="label label-success">host:www.baidu.com</span>
              <span class="label label-success">plugin:nmap</span>
              <span class="label label-success">status:finish</span>
            </div>
          </div>
        </form>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>名称</th>
            <th>目标数量</th>
            <th>插件</th>
            <th>状态</th>
            <th>漏洞数量</th>
            <th>时间戳</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.count }}</td>
            <td>
                {% for plugin in object.plugin.all %}
                <span class="label label-default">{{ plugin.name }}</span>
                {% endfor %}
            </td>
            <td>
                {% if object.status == 'S' %}
                <span class="label label-primary">{{ object.get_status_display }}</span>
                {% elif object.status == 'F' %}
                <span class="label label-success">{{ object.get_status_display }}</span>
                {% elif object.status == 'E' %}
                <span class="label label-danger">{{ object.get_status_display }}</span>
                {% endif %}
            </td>
            <td>
                <span class="label label-danger">高：2</span>
                <span class="label label-warning">中：3</span>
                <span class="label label-primary">低：2</span>
            </td>
            <td>{{ object.timestamp }}</td>
            <td>
              <a href="{% url 'task_details' %}" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> 详情 </a>
              <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> 编辑 </a>
              <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> 删除 </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="page-header"></div>
      <nav >
      {% if is_paginated %}
          <ul class="pager">
          {% if page_obj.has_previous %}
            <li class="previous"><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">上一页</a></li>
          {% endif %}
          {% if page_obj.has_next %}
            <li class="next"><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">下一页</a></li>
          {% endif %}
          </ul>
      {% endif %}
      </nav>

    </div>
{% endblock %}

naja_web/web_users/templates/widgets/input_option.html
{% if wrap_label %}<label class="{{ widget.attrs.sonclass }}" {% if widget.attrs.id %} for="{{ widget.attrs.id }}"{% endif %}>{% endif %}{% include "django/forms/widgets/input.html" %}<span class="{{ widget.attrs.grandsonclass }}">{% if wrap_label %} {{ widget.label }}</span></label>{% endif %}

naja_web/web_users/templates/widgets/multiple_input.html
{% with id=widget.attrs.id %}<div{% if id %} id="{{ id }}"{% endif %}{% if widget.attrs.class %} class="{{ widget.attrs.class }}"{% endif %}>{% for group, options, index in widget.optgroups %}{% if group %}
  {{ group }}<div{% if id %} id="{{ id }}_{{ index }}"{% endif %}>{% endif %}{% for option in options %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group %}
  </div>{% endif %}{% endfor %}
</div>{% endwith %}